version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    pull_policy: never
    build:
      context: ./requirements/mariadb/
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - "3306"
    networks:
      - hyecheon-network
    env_file: .env
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    pull_policy: never
    env_file: .env
    build:
      context: ./requirements/wordpress/
      args:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        WORDPRESS_PATH: ${WORDPRESS_PATH}
        WORDPRESS_TITLE: ${WORDPRESS_TITLE}
        WORDPRESS_URL: ${WORDPRESS_URL}
        WORDPRESS_WWW: ${WORDPRESS_WWW}
        WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
        WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
        WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
        WORDPRESS_USER: ${WORDPRESS_USER}
        WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
        WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wp-volume:/var/www/html
    expose:
      - "9000"
    networks:
      - hyecheon-network
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx
    pull_policy: never
    build: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - hyecheon-network
    volumes:
      - wp-volume:/var/www/html
    restart: always

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
#      device: /Users/hyecheon/dbvolume
      device: /Users/min/Desktop/code/42cursus/inception/srcs/dbvolume

  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
#      device: /Users/hyecheon/wpvolume
      device: /Users/min/Desktop/code/42cursus/inception/srcs/wpvolume

networks:
  hyecheon-network:
    driver: bridge