version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    pull_policy: never
    build: ./requirements/mariadb/
    env_file: .env
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
    expose:
      - "3306"
    networks:
      - hyecheon-network
    restart: always
    volumes:
      - db-volume:/var/lib/mysql

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress
    pull_policy: never
    build:
      context: ./requirements/wordpress/
      args:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file: .env
    expose:
      - "9000"
    networks:
      - hyecheon-network
    restart: always
    volumes:
      - wp-volume:/var/www/html

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    image: nginx
    pull_policy: never
    build: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - hyecheon-network
    volumes:
      - wp-volume:/var/www/html
    restart: always

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind # 바인드 마운트: 로컬 파일 시스템 디렉토리를 볼륨으로 사용.
      device: /home/hyecheon/data/dbvolume
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hyecheon/data/wpvolume

networks:
  hyecheon-network:
    driver: bridge # 호스트에 연결된 브리지 네트워크를 생성. 컨테이너는 브리지를 통해 네트워크와 통신.