version: "3"

services:
  mariadb:
    image: alpinelinux/mariadb:latest
    container_name: mariadb
    expose:
      - "3306"
    networks:
      - hyecheon-network
#    build:
#      context: ./requirements/mariadb/Dockerfile
    env_file: .env
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db-volume:/home
    restart: always

  wordpress:
    image: wordpress:6.4.3-fpm-alpine
    container_name: wordpress
#    build:
#      context: ./requirements/wordpress/Dockerfile
    depends_on:
      - mariadb
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wp-volume:/home
    expose:
      - "9000"
    networks:
      - hyecheon-network
    restart: always

  nginx:
    image: nginx:alpine3.18
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - hyecheon-network
    volumes:
      - wp-volume:/home
    restart: always
#    build:
#      context: ./requirements/nginx/Dockerfile

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/hyecheon/dbvolume
#      device: /Users/min/Desktop/code/42cursus/inception/srcs/dbvolume

  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/hyecheon/wpvolume
#      device: /Users/min/Desktop/code/42cursus/inception/srcs/wpvolume

networks:
  hyecheon-network:
    driver: bridge
